config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :moves, only: %i[edit]
  resources :games, only: %i[new index]

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'games#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :check_for_active_game, only: %i[index]

  def new
    session[:game] = Board.new
    redirect_to games_path
  end

  def index
    game =
      Board.from_grid(
        session[:game]['grid'],
        columns: session[:game]['columns'],
        rows:    session[:game]['rows']
      )

    render locals: { game: game }
  end

  private

  def check_for_active_game
    return if session[:game].present?

    session[:game] = Board.new
    redirect_to games_path
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def edit
    board =
      Board.from_grid(
        session[:game]['grid'],
        columns: session[:game]['columns'],
        rows:    session[:game]['rows']
      )

    board_manager = BoardManagerService.new(board)
    row = board_manager.insert(player: session[:player], column: move_param.to_i)
    session[:game] = board

    if WinningConditionService.new(board: board, player: session[:player], position: { column: move_param.to_i, row: row }).won?
      redirect_to games_path, notice: "Player #{session[:player]} won!"
      return
    end

    swap_players
    redirect_to(games_path)
  rescue BoardManagerService::IllegalMoveError
    flash[:error] = 'Illegal move'
    redirect_to games_path
  end

  private

  def move_param
    params.require(:id)
  end

  def swap_players
    session[:player] = session[:player] == 'X' ? '0' : 'X'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/games/index.html.haml
%h1
  Current Player:
  = session[:player]

.container.flex.flex-row.flex-nowrap.justify-center
  - game.all_columns.each_with_index do |column, index|
    .container.flex-column.flex-nowrap{ class: "column-#{index}" }
      = link_to 'Move Here', edit_move_path(id: index), class: 'move', data: { remote: false }
      - column.each_with_index do |cell, cindex|
        .cell.border-black.border{ class: "#{index}-#{cindex}" }
          = cell || '-'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Four</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% flash.each do |level, error| %>
        <div class="<%= level %>">
          <%= error %>
        </div>
      <% end %>
    </header>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>